import {
  si1password,
  siAsana,
  siAutocad,
  siAutodesk,
  siAutodeskmaya,
  siBitwarden,
  siBlender,
  siBox,
  siCalendly,
  siClaude,
  siCloudflare,
  siConfluence,
  siCursor,
  siDatagrip,
  siDeepl,
  siDocker,
  siDropbox,
  siFigma,
  siGithub,
  siGithubcopilot,
  siGitlab,
  siGooglegemini,
  siGrammarly,
  siHoudini,
  siHubspot,
  siIntellijidea,
  siIntercom,
  siJetbrains,
  siJira,
  siLoom,
  siMiro,
  siNotion,
  siOkta,
  siPerforce,
  siPerplexity,
  siPostman,
  siPycharm,
  siRider,
  siSketch,
  siUnity,
  siUnrealengine,
  siWebex,
  siWebstorm,
  siZendesk,
  siZoom,
  type SimpleIcon,
} from 'simple-icons';

/**
 * Brand marks from Simple Icons (CC0), keyed by slug. Imported individually so only these ship.
 * Brands Simple Icons has removed (Microsoft, Adobe, OpenAI, Slack…) use image files instead.
 */
export const SIMPLE_ICON_LOGOS: Record<string, SimpleIcon> = {
  '1password': si1password,
  asana: siAsana,
  autocad: siAutocad,
  autodeskmaya: siAutodeskmaya,
  autodesk: siAutodesk,
  bitwarden: siBitwarden,
  blender: siBlender,
  houdini: siHoudini,
  perforce: siPerforce,
  unity: siUnity,
  unrealengine: siUnrealengine,
  box: siBox,
  calendly: siCalendly,
  claude: siClaude,
  cloudflare: siCloudflare,
  confluence: siConfluence,
  cursor: siCursor,
  datagrip: siDatagrip,
  deepl: siDeepl,
  docker: siDocker,
  dropbox: siDropbox,
  figma: siFigma,
  github: siGithub,
  githubcopilot: siGithubcopilot,
  gitlab: siGitlab,
  googlegemini: siGooglegemini,
  grammarly: siGrammarly,
  hubspot: siHubspot,
  intellijidea: siIntellijidea,
  intercom: siIntercom,
  jetbrains: siJetbrains,
  jira: siJira,
  loom: siLoom,
  miro: siMiro,
  notion: siNotion,
  okta: siOkta,
  perplexity: siPerplexity,
  postman: siPostman,
  pycharm: siPycharm,
  rider: siRider,
  sketch: siSketch,
  webex: siWebex,
  webstorm: siWebstorm,
  zendesk: siZendesk,
  zoom: siZoom,
};
